# Generated by Django 5.0.3 on 2024-08-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Pharmacist', 'Pharmacist'), ('Admin', 'Admin')], max_length=150, null=True),
        ),
    ]
