# Generated by Django 5.0.3 on 2024-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
