# Generated by Django 5.0.3 on 2024-07-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prescription_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
