# Generated by Django 5.0.3 on 2024-08-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedication',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedication',
            name='frequency',
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='instructions',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
