# Generated by Django 5.0.3 on 2024-08-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='package_size',
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
